name: Basic CI/CD Pipeline

# Kích hoạt pipeline khi có push hoặc pull request vào nhánh main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Build và Test ứng dụng Node.js
  build_and_test:
    runs-on: ubuntu-latest # Chạy trên máy ảo Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master # Sử dụng Snyk Action
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Lấy token từ GitHub Secrets
        with:
          command: monitor
  # Job 2: Build và Đẩy Docker image
  build_and_push_docker:
    needs: build_and_test # Job này chỉ chạy sau khi 'build_and_test' thành công
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-ci-cd-app:latest
